#include Agent_BaseFunctionality
#include AgentExtension_Inventory_Clonk
#include AgentExtension_Ready_Clonk
#include AgentExtension_Senses_RangedVision
#include AgentExtension_Senses_SpawnPoint
#include AgentExtension_Movement_Clonk
